FROM ubi8/ubi:8.3

MAINTAINER Fruck <fruckman@gmail.com>

LABEL description="A custom apple pie"

RUN yum install -y httpd && \
	yum clean all

RUN echo "Hello from YW" > /var/www/html/index.html

EXPOSE 80

CMD ["sh", "-c", "httpd -D FOREGROUND -d /etc/httpd -e warn"]
#CMD ["httpd", "-D", "FOREGROUND", "-d", "/etc/httpd", "-e", "warn"]
